require("plugins._packer")

require("plugins._git")
require("plugins._nvim_cmp")
require("plugins._nvim_dap")
require("plugins._lualine")
--require("plugins._lspconfig")
require("plugins._rust_tools")
require("plugins._kommentary")
require("plugins._treesitter")
require("plugins._nvim_scrollbar")
require("plugins._nvim_telescope")
require("plugins._color")
require("plugins._vimwiki")
require("plugins._barbar")
